/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  THE VEIL'S SILK
 * ─────────────────────────────────────────────────────────────────────────────
 *  Builds the loading veil's background from a real photograph of silk, plus a
 *  20px blur of it inlined as a data URI.
 *
 *  ── WHY A PHOTOGRAPH, AFTER ALL ───────────────────────────────────────────
 *  The first version drew the silk in CSS gradients, to keep the loading
 *  screen off the network. It was honest engineering and it looked like
 *  corduroy: gradients repeat, and silk does not. Procedural fabric was tried
 *  next — SVG feTurbulence lit with diffuse and specular passes — and got as
 *  far as convincing folds with unconvincing colour. Real woven silk with
 *  zari is a photograph or it is nothing.
 *
 *  ── AND WHY IT STILL DOES NOT COST A FRAME ────────────────────────────────
 *  The veil's whole job is to cover the page WHILE it loads, so it must never
 *  itself be a thing being waited for. Two outputs solve that:
 *
 *    · veil-silk.webp   the real photograph, ~1600px, quality 72
 *    · veil-blur.txt    a 20px version as a base64 data URI, inlined straight
 *                       into the CSS — so the first painted frame is already
 *                       red silk, at zero network cost, and the photograph
 *                       resolves on top of it whenever it arrives.
 *
 *  On a slow connection the visitor sees the blur and never an empty box. On a
 *  fast one they never see the blur at all.
 *
 *  Run: npm run build:veil
 * ─────────────────────────────────────────────────────────────────────────────
 */
import { writeFile, mkdir } from "node:fs/promises";
import sharp from "sharp";

/**
 * The source frame and the region taken from it.
 *
 * `ritual-06-gold` is a bride beneath a red veil; this box is the fabric to
 * the right of her, which is silk and gold bokeh and nothing else. A veil that
 * is a photograph of a FACE would compete with the wordmark laid over it, and
 * would put a stand-in bride on the first frame of the site.
 */
const SOURCE = "public/portfolio/ritual-06-gold.webp";
/**
 * Height stops at 880, not 1100. Below that line the bride's mehendi hand
 * enters the frame — invisible on a desktop crop, but a portrait viewport
 * shows the full height and put a hand in the corner of the opening.
 */
const REGION = { left: 1150, top: 0, width: 850, height: 880 };

const OUT_IMG = "public/veil/veil-silk.webp";
const OUT_BLUR = "src/content/veil-blur.json";

await mkdir("public/veil", { recursive: true });

const region = sharp(SOURCE).extract(REGION);

const full = await region
  .clone()
  // Upscaled from 850px. Lanczos plus a whisker of blur reads as depth of
  // field rather than as an upscale, which is what a veil wants anyway.
  .resize({ width: 1600, kernel: "lanczos3" })
  .blur(0.5)
  .modulate({ brightness: 1.06, saturation: 1.04 })
  .webp({ quality: 72 })
  .toFile(OUT_IMG);

const blur = await region
  .clone()
  .resize({ width: 20 })
  .modulate({ brightness: 1.06, saturation: 1.04 })
  .webp({ quality: 40 })
  .toBuffer();

const dataUri = `data:image/webp;base64,${blur.toString("base64")}`;

await writeFile(
  OUT_BLUR,
  `${JSON.stringify(
    {
      _comment: "Generated by scripts/build-veil.mjs. Do not edit by hand.",
      generatedAt: new Date().toISOString(),
      src: `/${OUT_IMG.replace(/^public\//, "")}`,
      blurDataURL: dataUri,
    },
    null,
    2,
  )}\n`,
);

console.log(`✓ ${OUT_IMG}  ${full.width}×${full.height}  ${(full.size / 1024).toFixed(0)} KB`);
console.log(`✓ ${OUT_BLUR}  inline blur ${(dataUri.length / 1024).toFixed(1)} KB`);
